update to Meteor 0.9.3.1
The meteor cli tool updated itself, then `meteor run` started erroring out like this:

    $ meteor run
    Figuring out the best package versions to use. This may take a moment.
    Refreshing package metadata. This may take a moment.
    Could not resolve the specified constraints for this project:
    Error: conflict: logging can't be satisfied

`meteor update` made it work.